// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:collect_attendance/data/models/attendance_record_model.dart';
import 'package:collect_attendance/data/models/lecture_model.dart';
import 'package:collect_attendance/data/models/lecture_status.dart';
import 'package:collect_attendance/data/models/professor_model.dart';
import 'package:collect_attendance/data/models/student_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AttendanceRecordModelAdapter());
    registerAdapter(LectureModelAdapter());
    registerAdapter(LectureStatusAdapter());
    registerAdapter(ProfessorModelAdapter());
    registerAdapter(StudentModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AttendanceRecordModelAdapter());
    registerAdapter(LectureModelAdapter());
    registerAdapter(LectureStatusAdapter());
    registerAdapter(ProfessorModelAdapter());
    registerAdapter(StudentModelAdapter());
  }
}
